### ISSUE TITLE
Include binaries in releases

### ISSUE THREAD

**Issue by TheJaredWilcurt** [sass/sassc#154] opened 2015-11-17 18:54 UTC
It's not uncommon for the [releases](https://github.com/sass/sassc/releases) page on GitHub to include downloadable built versions of a project.

Not everyone wants to _develop_ SassC, most people just want to _use_ it. Forcing everyone to download and build the source is just a big pain in the ass.

I could kind of see an argument if your instructions were

> "On OSX run `make`, on Ubuntu run `makefile`, on Windows double-click `make.bat`".

Something where each OS has [1-3 very easy steps](https://github.com/flif-hub/FLIF#build-instructions). But your instructions aren't that simple, and I don't think it's an unreasonable expectation that those with known-good environments (who are working on it), be the ones to do a build for that release.

Also for people with just command line experience, but no programming knowledge, it gives them a trustworthy latest copy of the executable, so they don't need to [download outdated, potentially unsafe copies](http://www.xamount.ca/pages/sassc.html) from third parties (that's the first link on Google).

**Comment by niutech** [comment] 2016-01-25 16:47
+1 for Windows binaries. For now, we can get them from [here](http://libsass.ocbnet.ch/installer/), but it should be at least added to the README.

**Comment by ari** [comment] 2016-04-02 10:15
I think this is just a more demanding duplicate of #157

**Comment by mgreter** [comment] 2016-12-10 19:21
Closing as duplicate of #157

**Closed by mgreter** 2016-12-10 19:21 UTC
